trigger: none

name: '$(GitVersion.MajorMinorPatch)-pr$(System.PullRequest.PullRequestId)-$(Rev:r)'

pool:
  vmImage: 'windows-latest'

steps:
- task: gitversion/setup@0
  inputs:
    versionSpec: '5.x'
  
- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: 'pipelines/GitVersion.yml'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    packagesToPack: '$(Build.Repository.LocalPath)/src/**/*.Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: '$(Build.Repository.LocalPath)/src/**/*.csproj'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'packages'
    publishLocation: 'Container'
